variables:
    GIT_STRATEGY: clone

stages:
  - deploy

deploy checks codes to shared reframe directory:
  stage: deploy
  tags:
    - shell.login3.pi.sjtu.edu.cn
  only:
    - master
    - merge_request
  script:
    - sudo rsync -avr --progress sjtuhpc-checks /lustre/share/tmp/reframe/