variables:
    GIT_STRATEGY: clone

stages:
  - deploy

deploy checks codes to shared reframe directory:
  stage: deploy
  tags:
    - shell.login3.pi.sjtu.edu.cn
  only:
    - master
    - merge_request
  before_script:
    - git clone https://github.com/eth-cscs/reframe.git
  script:
    - mv sjtuhpc-checks reframe/
    - cp config/sjtupi2.py reframe/config && ln -s reframe/config/sjtupi2.py  reframe/settings.py
    - sudo rsync -avr --progress reframe /lustre/share/tmp/